### ISSUE TITLE
Develop a logo for the Hyperloot project

### ISSUE THREAD

**Issue by PonyUnicorn** [HyperLootProtocol/Hyperloot-Branding#1]

**Comment by PonyUnicorn** [comment]
Draft 1 

![hyperloot logo_2](https://user-images.githubusercontent.com/16205376/42276020-714ba880-7f92-11e8-8fd1-e07d270ee405.png)
![hyperloot logo_1](https://user-images.githubusercontent.com/16205376/42276021-716bc67e-7f92-11e8-9077-00483f54151a.png)

**Comment by valeryvaskabovich** [comment]
I'd choose #1  because #2 reminds me one famous company with a bunch of photo apps popular on mobile

**Comment by vick416** [comment]
I think the logo need to use something to do with the movement and actually loot, and it should assiciate with the gaming theme, you may want to use a more strict font. 
May be to use a picture of the case / the sword / the letter H in the centre and beside him, flying a rocket with a tail of the speed or rotation of the warp jump.
Game developers often transfer part of their name to the logo image.

**Comment by PonyUnicorn** [comment]
Hey Vick, Thatks so much for the comment! It's a great point, however in this case we chose consciously to go with a more flat style. It's a platform, so first and foremost we wanted it to be readable as a product. This is due to the fact that it should look good on any partnering materials, which are games, henceforth have game-themed logos. That beinf said we really cherish yuour inpur and if we get more feedback like that we will definitely be able to take another look at the concept.

**Comment by angryscout** [comment]
I think both logos are Ok for draft, but there are a lot of strange moments in them. First logo have very inconspicuous bridge, and in low version it doesn`t read like H, also font of Hyperloop now is just terrifying. I really like colours of work, but fonts in both works makes me sad. If you remove all mistakes it will be a better one, than old logo, but today it`s on same level.

**Comment by PonyUnicorn** [comment]
Hey @angryscout , thanks for taking the time and providing feedback! It's great to hear your thought. We've decided to move forward with the second option for now, but if you could make sopme font suggestions - that would be quite useful!
